import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for the textbook
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module1-ros2/chapter1-architecture',
        'module1-ros2/chapter2-python-packages',
        'module1-ros2/chapter3-urdf-modeling',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module2-digital-twin/chapter1-gazebo-intro',
        'module2-digital-twin/chapter2-urdf-sdf-modeling',
        'module2-digital-twin/chapter3-sensor-unity-integration',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module3-nvidia-isaac/chapter1-isaac-sim-intro',
        'module3-nvidia-isaac/chapter2-isaac-ros-tools',
        'module3-nvidia-isaac/chapter3-nav2-bipedal-planning',
      ],
    },
  ],
};

export default sidebars;
